remote_theme: pmarsceill/just-the-docs

title: OHDSI ETL PRIAS
description: Documentation of the ETL of PRIAS data to OMOP

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Source code (private)":
    - "//github.com/thehyve/ohdsi-etl-prias"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

footer_content: "OHDSI ETL PRIAS v0.1 | Copyright &copy; The Hyve</a>"